services:
  - type: worker
    name: ascomp-export-worker
    env: node
    buildCommand: pnpm install && bunx prisma generate
    startCommand: pnpm run worker:export
    envVars:
      - key: NODE_ENV
        value: production
      - key: REDIS_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: BLOB_READ_WRITE_TOKEN
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_CLIENT_ID
        sync: false
      - key: GMAIL_CLIENT_SECRET
        sync: false
      - key: GMAIL_REFRESH_TOKEN
        sync: false
